services:
  mi-mongo:
    image: mongo:latest
    container_name: mi-mongo
    ports:
      - "27017:27017"
    # Añadimos el volumen apuntando a la ruta interna de Mongo
    volumes:
      - mongo_data:/data/db

  bayeta-app:
    build: .
    container_name: bayeta-app
    ports:
      - "5000:5000"
    depends_on:
      - mi-mongo

# Declaramos el volumen al final para que Docker lo cree y gestione
volumes:
  mongo_data:
